import { FormationType, PlayerNode, TacticalScenario, DrillPlan, BiomechanicalLandmark } from '../types/nexus';

export const FORMATION_COORDINATES: Record<FormationType, { home: Omit<PlayerNode, 'id' | 'team'>[]; away: Omit<PlayerNode, 'id' | 'team'>[] }> = {
  '4-3-3': {
    home: [
      { number: 1, name: 'GK (Ederson)', role: 'Sweeper Keeper', x: 8, y: 50 },
      { number: 2, name: 'RB (Walker)', role: 'Inverted RB', x: 25, y: 82 },
      { number: 5, name: 'CB (Dias)', role: 'Covering CB', x: 22, y: 62 },
      { number: 6, name: 'CB (Akanji)', role: 'Ball-Playing CB', x: 22, y: 38 },
      { number: 3, name: 'LB (Gvardiol)', role: 'Wide Back', x: 25, y: 18 },
      { number: 16, name: 'DM (Rodri)', role: 'Deep Anchor', x: 40, y: 50 },
      { number: 17, name: 'RCM (De Bruyne)', role: 'Half-Space #8', x: 55, y: 68 },
      { number: 20, name: 'LCM (Bernardo)', role: 'Interior #8', x: 55, y: 32 },
      { number: 47, name: 'RW (Foden)', role: 'Inverted Winger', x: 72, y: 80 },
      { number: 9, name: 'ST (Haaland)', role: 'Advanced Forward', x: 78, y: 50 },
      { number: 11, name: 'LW (Doku)', role: 'Touchline Winger', x: 72, y: 20 },
    ],
    away: [
      { number: 1, name: 'GK (Courtois)', role: 'Goalkeeper', x: 92, y: 50 },
      { number: 2, name: 'RB (Carvajal)', role: 'Fullback', x: 75, y: 18 },
      { number: 3, name: 'CB (Militao)', role: 'Stopper CB', x: 78, y: 38 },
      { number: 4, name: 'CB (Rudiger)', role: 'Physical CB', x: 78, y: 62 },
      { number: 23, name: 'LB (Mendy)', role: 'Defensive LB', x: 75, y: 82 },
      { number: 14, name: 'DM (Tchouaméni)', role: 'Anchor DM', x: 62, y: 50 },
      { number: 15, name: 'RCM (Valverde)', role: 'Box-to-Box #8', x: 50, y: 32 },
      { number: 5, name: 'LCM (Bellingham)', role: 'Free Roaming #10', x: 48, y: 66 },
      { number: 11, name: 'RW (Rodrygo)', role: 'Inside Forward', x: 30, y: 22 },
      { number: 9, name: 'ST (Mbappé)', role: 'Poacher/Sprinter', x: 26, y: 50 },
      { number: 7, name: 'LW (Vinícius)', role: 'Transition Winger', x: 30, y: 78 },
    ],
  },
  '3-2-4-1': {
    home: [
      { number: 1, name: 'GK', role: 'Sweeper Keeper', x: 8, y: 50 },
      { number: 2, name: 'RCB', role: 'Wide Stopper', x: 24, y: 74 },
      { number: 3, name: 'CCB', role: 'Central Sweeper', x: 20, y: 50 },
      { number: 4, name: 'LCB', role: 'Wide Stopper', x: 24, y: 26 },
      { number: 5, name: 'RDM', role: 'Inverted Fullback-DM', x: 42, y: 64 },
      { number: 6, name: 'LDM', role: 'Deep Controller', x: 42, y: 36 },
      { number: 7, name: 'RM', role: 'Touchline Wing', x: 62, y: 88 },
      { number: 8, name: 'RAM', role: 'Right Half-Space #10', x: 65, y: 62 },
      { number: 10, name: 'LAM', role: 'Left Half-Space #10', x: 65, y: 38 },
      { number: 11, name: 'LM', role: 'Touchline Wing', x: 62, y: 12 },
      { number: 9, name: 'ST', role: 'Focal Point #9', x: 82, y: 50 },
    ],
    away: [
      { number: 1, name: 'GK', role: 'Goalkeeper', x: 92, y: 50 },
      { number: 2, name: 'RWB', role: 'Wingback', x: 74, y: 14 },
      { number: 4, name: 'RCB', role: 'Center Back', x: 78, y: 32 },
      { number: 5, name: 'CB', role: 'Central Defender', x: 80, y: 50 },
      { number: 6, name: 'LCB', role: 'Center Back', x: 78, y: 68 },
      { number: 3, name: 'LWB', role: 'Wingback', x: 74, y: 86 },
      { number: 8, name: 'RCM', role: 'Central Midfielder', x: 60, y: 35 },
      { number: 10, name: 'LCM', role: 'Central Midfielder', x: 60, y: 65 },
      { number: 7, name: 'RW', role: 'Second Striker', x: 42, y: 30 },
      { number: 9, name: 'ST', role: 'Center Forward', x: 34, y: 50 },
      { number: 11, name: 'LW', role: 'Second Striker', x: 42, y: 70 },
    ],
  },
  '4-2-3-1': {
    home: [
      { number: 1, name: 'GK', role: 'Goalkeeper', x: 8, y: 50 },
      { number: 2, name: 'RB', role: 'Right Back', x: 26, y: 84 },
      { number: 4, name: 'RCB', role: 'Center Back', x: 22, y: 62 },
      { number: 5, name: 'LCB', role: 'Center Back', x: 22, y: 38 },
      { number: 3, name: 'LB', role: 'Left Back', x: 26, y: 16 },
      { number: 6, name: 'RDM', role: 'Double Pivot', x: 38, y: 62 },
      { number: 8, name: 'LDM', role: 'Double Pivot', x: 38, y: 38 },
      { number: 7, name: 'RAM', role: 'Attacking Midfielder', x: 60, y: 78 },
      { number: 10, name: 'CAM', role: 'Central Number 10', x: 58, y: 50 },
      { number: 11, name: 'LAM', role: 'Attacking Midfielder', x: 60, y: 22 },
      { number: 9, name: 'ST', role: 'Lone Striker', x: 78, y: 50 },
    ],
    away: [
      { number: 1, name: 'GK', role: 'Goalkeeper', x: 92, y: 50 },
      { number: 2, name: 'RB', role: 'Fullback', x: 74, y: 16 },
      { number: 4, name: 'RCB', role: 'Center Back', x: 78, y: 38 },
      { number: 5, name: 'LCB', role: 'Center Back', x: 78, y: 62 },
      { number: 3, name: 'LB', role: 'Fullback', x: 74, y: 84 },
      { number: 6, name: 'RDM', role: 'Defensive Midfield', x: 62, y: 38 },
      { number: 8, name: 'LDM', role: 'Defensive Midfield', x: 62, y: 62 },
      { number: 7, name: 'RW', role: 'Right Wing', x: 44, y: 22 },
      { number: 10, name: 'CAM', role: 'Attacking Mid', x: 42, y: 50 },
      { number: 11, name: 'LW', role: 'Left Wing', x: 44, y: 78 },
      { number: 9, name: 'ST', role: 'Target Man', x: 25, y: 50 },
    ],
  },
  '5-3-2': {
    home: [
      { number: 1, name: 'GK', role: 'Goalkeeper', x: 8, y: 50 },
      { number: 2, name: 'RWB', role: 'Right Wingback', x: 26, y: 88 },
      { number: 4, name: 'RCB', role: 'Right Center Back', x: 20, y: 66 },
      { number: 5, name: 'CB', role: 'Sweeper CB', x: 18, y: 50 },
      { number: 6, name: 'LCB', role: 'Left Center Back', x: 20, y: 34 },
      { number: 3, name: 'LWB', role: 'Left Wingback', x: 26, y: 12 },
      { number: 8, name: 'RCM', role: 'Central Midfielder', x: 44, y: 68 },
      { number: 16, name: 'CM', role: 'Anchor Pivot', x: 40, y: 50 },
      { number: 10, name: 'LCM', role: 'Central Midfielder', x: 44, y: 32 },
      { number: 9, name: 'RST', role: 'Striker', x: 72, y: 60 },
      { number: 11, name: 'LST', role: 'Striker', x: 72, y: 40 },
    ],
    away: [
      { number: 1, name: 'GK', role: 'Goalkeeper', x: 92, y: 50 },
      { number: 2, name: 'RWB', role: 'Wingback', x: 76, y: 12 },
      { number: 4, name: 'RCB', role: 'Right CB', x: 82, y: 32 },
      { number: 5, name: 'CB', role: 'Central CB', x: 84, y: 50 },
      { number: 6, name: 'LCB', role: 'Left CB', x: 82, y: 68 },
      { number: 3, name: 'LWB', role: 'Wingback', x: 76, y: 88 },
      { number: 8, name: 'RCM', role: 'Midfield Carrier', x: 60, y: 32 },
      { number: 14, name: 'CM', role: 'Shield Midfielder', x: 62, y: 50 },
      { number: 10, name: 'LCM', role: 'Midfield Carrier', x: 60, y: 68 },
      { number: 9, name: 'RST', role: 'Counter Striker', x: 35, y: 38 },
      { number: 7, name: 'LST', role: 'Counter Striker', x: 35, y: 62 },
    ],
  },
  '4-4-2 Diamond': {
    home: [
      { number: 1, name: 'GK', role: 'Goalkeeper', x: 8, y: 50 },
      { number: 2, name: 'RB', role: 'Attacking Fullback', x: 28, y: 86 },
      { number: 4, name: 'RCB', role: 'Center Back', x: 22, y: 62 },
      { number: 5, name: 'LCB', role: 'Center Back', x: 22, y: 38 },
      { number: 3, name: 'LB', role: 'Attacking Fullback', x: 28, y: 14 },
      { number: 6, name: 'DM', role: 'Base of Diamond', x: 36, y: 50 },
      { number: 8, name: 'RCM', role: 'Right Shuttler', x: 50, y: 68 },
      { number: 7, name: 'LCM', role: 'Left Shuttler', x: 50, y: 32 },
      { number: 10, name: 'CAM', role: 'Tip of Diamond #10', x: 64, y: 50 },
      { number: 9, name: 'RST', role: 'Right Striker', x: 78, y: 62 },
      { number: 11, name: 'LST', role: 'Left Striker', x: 78, y: 38 },
    ],
    away: [
      { number: 1, name: 'GK', role: 'Goalkeeper', x: 92, y: 50 },
      { number: 2, name: 'RB', role: 'Fullback', x: 72, y: 14 },
      { number: 4, name: 'RCB', role: 'Center Back', x: 78, y: 38 },
      { number: 5, name: 'LCB', role: 'Center Back', x: 78, y: 62 },
      { number: 3, name: 'LB', role: 'Fullback', x: 72, y: 86 },
      { number: 6, name: 'DM', role: 'Shield', x: 64, y: 50 },
      { number: 8, name: 'RCM', role: 'Shuttler', x: 50, y: 32 },
      { number: 7, name: 'LCM', role: 'Shuttler', x: 50, y: 68 },
      { number: 10, name: 'CAM', role: 'Playmaker', x: 36, y: 50 },
      { number: 9, name: 'RST', role: 'Front Two', x: 24, y: 38 },
      { number: 11, name: 'LST', role: 'Front Two', x: 24, y: 62 },
    ],
  },
  '3-4-2-1': {
    home: [
      { number: 1, name: 'GK', role: 'Sweeper Keeper', x: 8, y: 50 },
      { number: 2, name: 'RCB', role: 'Right CB', x: 24, y: 72 },
      { number: 4, name: 'CCB', role: 'Central CB', x: 20, y: 50 },
      { number: 3, name: 'LCB', role: 'Left CB', x: 24, y: 28 },
      { number: 7, name: 'RWB', role: 'Right Wingback', x: 46, y: 88 },
      { number: 6, name: 'RCM', role: 'Pivot #1', x: 42, y: 60 },
      { number: 8, name: 'LCM', role: 'Pivot #2', x: 42, y: 40 },
      { number: 11, name: 'LWB', role: 'Left Wingback', x: 46, y: 12 },
      { number: 10, name: 'RAM', role: 'Inverted #10', x: 65, y: 65 },
      { number: 17, name: 'LAM', role: 'Inverted #10', x: 65, y: 35 },
      { number: 9, name: 'ST', role: 'Center Forward', x: 80, y: 50 },
    ],
    away: [
      { number: 1, name: 'GK', role: 'Goalkeeper', x: 92, y: 50 },
      { number: 2, name: 'RCB', role: 'Right CB', x: 76, y: 28 },
      { number: 4, name: 'CCB', role: 'Central CB', x: 80, y: 50 },
      { number: 3, name: 'LCB', role: 'Left CB', x: 76, y: 72 },
      { number: 7, name: 'RWB', role: 'Right Wingback', x: 54, y: 12 },
      { number: 6, name: 'RCM', role: 'Midfield Pivot', x: 58, y: 40 },
      { number: 8, name: 'LCM', role: 'Midfield Pivot', x: 58, y: 60 },
      { number: 11, name: 'LWB', role: 'Left Wingback', x: 54, y: 88 },
      { number: 10, name: 'RAM', role: 'Inside Forward', x: 35, y: 35 },
      { number: 17, name: 'LAM', role: 'Inside Forward', x: 35, y: 65 },
      { number: 9, name: 'ST', role: 'Striker', x: 20, y: 50 },
    ],
  },
};

export const TACTICAL_SCENARIOS: TacticalScenario[] = [
  {
    id: 'ucl-2026-final',
    title: '2026 UCL Final: Man City vs Real Madrid',
    year: 2026,
    competition: 'UEFA Champions League Final',
    matchContext: 'Minute 73. Real Madrid leading 1-0 via Mbappé transition. Man City pinned Madrid into a 5-3-2 low-block with 68% possession but struggling to breach half-spaces.',
    homeTeam: 'Manchester City',
    awayTeam: 'Real Madrid',
    homeFormation: '3-2-4-1',
    awayFormation: '5-3-2',
    homeScore: 0,
    awayScore: 1,
    minute: 73,
    keyTacticalChallenge: 'Bypassing the low-block double pivot without getting exposed to Vinicius/Mbappé 40-meter counter sprints.',
    initialHomePlayers: FORMATION_COORDINATES['3-2-4-1'].home.map((p, i) => ({ ...p, id: `home-${i + 1}`, team: 'home' })),
    initialAwayPlayers: FORMATION_COORDINATES['5-3-2'].away.map((p, i) => ({ ...p, id: `away-${i + 1}`, team: 'away' })),
  },
  {
    id: 'arsenal-press-2026',
    title: 'Premier League Title Decider: Arsenal High Press vs Transition',
    year: 2026,
    competition: 'Premier League Matchday 36',
    matchContext: 'Minute 38. Arsenal executing an aggressive 4-3-3 man-oriented press (PPDA 5.9). Opponent attempts to bypass press using direct chipped balls into half-spaces.',
    homeTeam: 'Arsenal FC',
    awayTeam: 'Liverpool FC',
    homeFormation: '4-3-3',
    awayFormation: '4-2-3-1',
    homeScore: 1,
    awayScore: 1,
    minute: 38,
    keyTacticalChallenge: 'Securing the 3+2 rest-defense structure while maintaining maximum forward pressing line compactness.',
    initialHomePlayers: FORMATION_COORDINATES['4-3-3'].home.map((p, i) => ({ ...p, id: `home-${i + 1}`, team: 'home' })),
    initialAwayPlayers: FORMATION_COORDINATES['4-2-3-1'].away.map((p, i) => ({ ...p, id: `away-${i + 1}`, team: 'away' })),
  },
  {
    id: 'worldcup-qualifier-2026',
    title: 'World Cup 2026 Warm-Up: High-Altitude Overload vs Compact Block',
    year: 2026,
    competition: 'International Showcase 2026',
    matchContext: 'Minute 61. Score 0-0. Defending team has dropped into a deep 5-4-1 shape, denying central progression and forcing predictable crosses.',
    homeTeam: 'Spain',
    awayTeam: 'Italy',
    homeFormation: '4-3-3',
    awayFormation: '5-3-2',
    homeScore: 0,
    awayScore: 0,
    minute: 61,
    keyTacticalChallenge: 'Creating third-man overloads in the half-space pockets to draw out Italian center-backs without conceding transition turnovers.',
    initialHomePlayers: FORMATION_COORDINATES['4-3-3'].home.map((p, i) => ({ ...p, id: `home-${i + 1}`, team: 'home' })),
    initialAwayPlayers: FORMATION_COORDINATES['5-3-2'].away.map((p, i) => ({ ...p, id: `away-${i + 1}`, team: 'away' })),
  },
];

export const BIOMECHANICAL_LANDMARKS: BiomechanicalLandmark[] = [
  {
    name: 'Striking Knee Flexion Angle',
    currentValue: 138.4,
    optimalValue: 142.0,
    unit: 'deg',
    status: 'optimal',
    description: 'Flexion angle at peak backswing before rapid quadriceps extension toward contact point.'
  },
  {
    name: 'Plant-Foot Ground Reaction Force (GRF)',
    currentValue: 1640,
    optimalValue: 1720,
    unit: 'N',
    status: 'optimal',
    description: 'Deceleration force anchored into turf to stabilize pelvic rotational axis.'
  },
  {
    name: 'Plant-Foot Lateral Distance to Ball',
    currentValue: 28.5,
    optimalValue: 26.0,
    unit: 'cm',
    status: 'suboptimal',
    description: 'Offset from ball centerline. High offset causes sliced contact and reduced exit velocity.'
  },
  {
    name: 'Torso Forward Pitch (Sagittal Lean)',
    currentValue: 17.5,
    optimalValue: 18.0,
    unit: 'deg',
    status: 'optimal',
    description: 'Upper torso pitch angle over ball center of mass to prevent sky-rocketing ball trajectory.'
  },
  {
    name: 'Pelvic Rotational Angular Velocity',
    currentValue: 642,
    optimalValue: 680,
    unit: 'deg/s',
    status: 'suboptimal',
    description: 'Rotational torque generated through kinetic chain uncoiling from core to hip.'
  },
  {
    name: 'Ankle Plantarflexion Lock',
    currentValue: 112.0,
    optimalValue: 115.0,
    unit: 'deg',
    status: 'optimal',
    description: 'Rigidity of talocrural joint to eliminate dampening during instep-to-leather energy transfer.'
  },
  {
    name: 'Ball Exit Velocity',
    currentValue: 116.8,
    optimalValue: 122.0,
    unit: 'km/h',
    status: 'optimal',
    description: 'Post-impact velocity derived from momentum conservation and coefficient of restitution.'
  },
  {
    name: 'Magnus Spin Rate',
    currentValue: 440,
    optimalValue: 450,
    unit: 'RPM',
    status: 'optimal',
    description: 'Topspin aerodynamic curl causing rapid downward dip over goalkeeper reach.'
  }
];

export const DRILL_PLANS: DrillPlan[] = [
  {
    id: 'drill-1',
    title: 'Isaac Sim 140-Yr Validated: Third-Man Half-Space Penetration Under Press',
    category: 'Half-Space Overload',
    duration: '22 Minutes',
    intensity: 'High',
    isaacSimCycles: '42,000 Self-Play Epochs',
    focusKinematic: 'Rapid hip uncoiling during open-body first touch (Target < 0.38s execution)',
    setupDimensions: '25m x 30m grid in final third with 2 mannequin defenders and 1 active presser',
    coachingPoints: [
      '**Decoy Movement:** Central striker must drop 3 steps into midfield to drag the center-back forward.',
      '**Body Orientation:** Receiving #8 must adopt 45° open stance toward the far corner flag.',
      '**One-Touch Blind-Side:** Play into the path of the sprinting winger behind the dislodged defender.',
      '**Rest-Defense Anchor:** Pivot #6 steps into the vacated space immediately to snuff out turnovers.'
    ],
    equipmentNeeded: ['6 Cones', '2 Tactical Mannequins', 'Smart Balls with IMU Sensors', 'Rebounder Board'],
    biomechanicalBenefits: [
      'Reduces deceleration joint shear stress by 34%',
      'Increases ball release speed by 0.22 seconds',
      'Optimizes kinetic chain transfer from hip to passing foot'
    ]
  },
  {
    id: 'drill-2',
    title: 'Inverted Fullback Central Shielding & 3+2 Rest-Defense Lockdown',
    category: 'Rest-Defense Stabilization',
    duration: '25 Minutes',
    intensity: 'Extreme',
    isaacSimCycles: '78,000 Self-Play Epochs',
    focusKinematic: 'Plant foot lateral grip & 90° rapid deceleration under physical contact',
    setupDimensions: 'Half-pitch setup with central 15m circle representing the central security zone',
    coachingPoints: [
      '**Inversion Timing:** Fullback tucks into the midfield pivot the moment the center-back crosses the halfway line.',
      '**Horizontal Distance:** Maintain exactly 12-14 meters separation between the two defensive pivots.',
      '**Cover Shadow Positioning:** Block forward vertical passing lanes into the opposing striker.',
      '**Counter-Press Response:** On loss of possession, execute a 4-meter aggressive squeeze within 2.8 seconds.'
    ],
    equipmentNeeded: ['Poles', 'Color-coded bibs', 'Video GPS vest trackers', 'Auditory pulse whistle'],
    biomechanicalBenefits: [
      'Minimizes hamstring eccentric strain during rapid backward recovery runs',
      'Enhances center-of-gravity stabilization during shoulder-to-shoulder collisions'
    ]
  },
  {
    id: 'drill-3',
    title: 'Markerless 3D Biomechanics: Driven Instep Strike Power Calibration',
    category: 'Biomechanic Strike Calibration',
    duration: '18 Minutes',
    intensity: 'Moderate',
    isaacSimCycles: '26,000 Self-Play Epochs',
    focusKinematic: '142° Striking Knee Extension & 1,720 N Ground Reaction Force plant',
    setupDimensions: 'Penalty box perimeter with automated target radar at 18-yard line',
    coachingPoints: [
      '**Approach Angle:** 35-40 degree diagonal approach to maximize pelvic rotational clearance.',
      '**Plant Foot Orientation:** Plant foot pointing precisely at the far post target with 26cm lateral clearance.',
      '**Torso Pitch:** Lock chest 18° forward over the ball to restrict aerodynamic lift.',
      '**Ankle Rigidity:** Full plantarflexion lock through the metatarsal strike point.'
    ],
    equipmentNeeded: ['Target Net Grids', 'High-Speed Camera / Cosmos Vision Sensor', 'Pressure Plate Mat'],
    biomechanicalBenefits: [
      'Generates +18.7% ball exit velocity (116+ km/h)',
      'Decreases ACL torsional strain by 29% through balanced plant dissipation',
      'Produces consistent 440 RPM topspin dip'
    ]
  }
];
